import { Button, ToggleSwitch, TextInput, Label, Card } from "flowbite-react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Nav from "../components/nav";
import { generatePassword } from "../services/generatePassword";
import { CopyToClipboard } from "react-copy-to-clipboard";

const Home: NextPage = () => {
  const [pw, setPw] = useState("");
  const [letters, setLetters] = useState(true);
  const [digits, setDigits] = useState(true);
  const [symbols, setSymbols] = useState(false);
  const [similarCharacters, setSimilarCharacters] = useState(false);
  const [passwordLength, setPasswordLength] = useState(10);

  useEffect(() => {
    setPw(
      generatePassword(
        letters,
        digits,
        symbols,
        similarCharacters,
        passwordLength
      )
    );
  }, [letters, digits, symbols, similarCharacters, passwordLength]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex flex-col items-center justify-center">
        <Nav />
        <div className="w-full max-w-sm">
          <Card>
            <div className="mb-3">
              <TextInput type="text" value={pw} onChange={()=>{}}/>
            </div>
            <div className="mb-3">
              <Label
                htmlFor="password-length"
                value={`Password Length: ${passwordLength}`}
              />
              <label
                htmlFor="minmax-range"
                className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
              ></label>
              <input
                id="minmax-range"
                type="range"
                min="8"
                max="110"
                onChange={(event) =>
                  setPasswordLength(Number(event.target.value))
                }
                value={passwordLength}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
              />
            </div>
            <div className="mb-3">
              <ToggleSwitch
                checked={letters}
                label="Letters (AaBb)"
                onChange={setLetters}
              />
            </div>
            <div className="mb-3">
              <ToggleSwitch
                checked={digits}
                label="Digits (1,2,3)"
                onChange={setDigits}
              />
            </div>
            <div className="mb-3">
              <ToggleSwitch
                checked={symbols}
                label="Symbols (!@#)"
                onChange={setSymbols}
              />
            </div>
            <div className="mb-3">
              <ToggleSwitch
                checked={similarCharacters}
                label="Similar characters (0O, Il)"
                onChange={setSimilarCharacters}
              />
            </div>
            <div>
              <CopyToClipboard text={pw}>
                <Button>Copy password</Button>
              </CopyToClipboard>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Home;
